---
version: '3'
services:
  greenwave: &greenwave
    build: .
    user: ${DEV_USER_ID:-1000}
    working_dir: /src
    env_file: ["docker/dev.env"]
    command: ["bash", "-c", "./docker/dev-command.sh"]
    volumes:
      - ./:/src:ro,z
      - ./docker/home:/home/dev:rw,z
      - ./docker/greenwave-settings.py:/etc/greenwave/settings.py:ro,z
      - ./conf/policies/:/etc/greenwave/policies/:ro,z
      - ./conf/subject_types/:/etc/greenwave/subject_types/:ro,z
    ports:
      - 127.0.0.1:8080:8080
    healthcheck: &greenwave-healthcheck
      test: >-
        /src/docker/docker-entrypoint.sh python -c 'import requests;
        requests.get("http://127.0.0.1:8080/healthcheck").raise_for_status();'
      interval: 1s
      timeout: 5s
      retries: 30
    depends_on:
      - memcached
      - resultsdb
      - waiverdb
      - statsd

  statsd:
    image: quay.io/prometheus/statsd-exporter:latest@sha256:4e7a1f00b9b23ef0c5b4fdbb7f4748bdc218cfdff04acc8033bc5b9f7c15009d
    ports:
      - 127.0.0.1:9102:9102  # http
      - 127.0.0.1:9125:9125  # statsd

  resultsdb-db: &resultsdb-db
    image: docker.io/library/postgres:18.1-alpine@sha256:aa6eb304ddb6dd26df23d05db4e5cb05af8951cda3e0dc57731b771e0ef4ab29
    restart: always
    env_file: ["docker/resultsdb-db.env"]
    healthcheck:
      <<: *greenwave-healthcheck
      test: "pg_isready -U postgres || exit 1"

  resultsdb:
    image: quay.io/redhat-user-workloads/exd-sp-rhel-wf-tenant/resultsdb:latest@sha256:c3862d7008c788b43e084e8b272c383b7f654913bbf9ea9bd2edc3f3b332f338
    environment:
      - GREENWAVE_LISTENERS=${GREENWAVE_LISTENERS:-1}
      - RESULTSDB_KAFKA_SASL_USERNAME=resultsdb
      - RESULTSDB_KAFKA_SASL_PASSWORD=resultsdb
    command: ["bash", "-c", "/start.sh"]
    volumes:
      - ./docker/home:/home/dev:rw,z
      - ./docker/resultsdb-command.sh:/start.sh:ro,z
      - ./docker/resultsdb-settings.py:/etc/resultsdb/settings.py:ro,z
      - ./docker/resultsdb.conf:/etc/httpd/conf.d/resultsdb.conf:ro,z
    ports:
      - 127.0.0.1:5001:5001
    healthcheck:
      <<: *greenwave-healthcheck
      test: >-
        /app/entrypoint.sh python -c 'import requests;
        requests.get("http://127.0.0.1:5001/api/v2.0/healthcheck").raise_for_status();'
    depends_on:
      - resultsdb-db

  waiverdb-db:
    <<: *resultsdb-db
    env_file: ["docker/waiverdb-db.env"]

  waiverdb:
    image: quay.io/redhat-user-workloads/exd-sp-rhel-wf-tenant/waiverdb:latest@sha256:84f032c6473510e2e374323d3f641cead1d66a0e03ccb16f1797a9829b80f784
    env_file: ["docker/waiverdb.env"]
    environment:
      - GREENWAVE_LISTENERS=${GREENWAVE_LISTENERS:-1}
    command: ["bash", "-c", "/start.sh"]
    volumes:
      - ./docker/home:/home/dev:rw,z
      - ./docker/waiverdb-command.sh:/start.sh:ro,z
      - ./docker/waiverdb-settings.py:/etc/waiverdb/settings.py:ro,z
      - ./docker/client_secrets.json:/etc/secret/client_secrets.json:ro,z
    ports:
      - 127.0.0.1:5004:5004
    user: '0'
    healthcheck:
      <<: *greenwave-healthcheck
      test: >-
        /app/entrypoint.sh python -c 'import requests;
        requests.get("http://127.0.0.1:5004/healthcheck").raise_for_status();'
    depends_on:
      - waiverdb-db

  memcached:
    image: "quay.io/factory2/memcached:latest@sha256:49d8e413ff528ce4be6320d432e3fcd7f691a8ad2c9b5784dc58b1054a1b45fb"
    ports:
      - 127.0.0.1:11211:11211

  resultsdb-listener:
    <<: *greenwave
    command:
      - "gunicorn"
      - "--reload"
      - "--workers=2"
      - "--threads=2"
      - "--bind=0.0.0.0:8082"
      - "--access-logfile=-"
      - "--enable-stdio-inheritance"
      - "greenwave.resultsdb_listener:app"
    ports:
      - 127.0.0.1:8082:8082
    deploy:
      replicas: ${GREENWAVE_LISTENERS:-1}

  waiverdb-listener:
    <<: *greenwave
    command:
      - "gunicorn"
      - "--reload"
      - "--workers=2"
      - "--threads=2"
      - "--bind=0.0.0.0:8083"
      - "--access-logfile=-"
      - "--enable-stdio-inheritance"
      - "greenwave.waiverdb_listener:app"
    ports:
      - 127.0.0.1:8083:8083
    deploy:
      replicas: ${GREENWAVE_LISTENERS:-1}

  message-broker:
    image: docker.io/apache/kafka:3.9.0@sha256:fbc7d7c428e3755cf36518d4976596002477e4c052d1f80b5b9eafd06d0fff2f
    hostname: message-broker
    restart: unless-stopped
    ports:
      - 127.0.0.1:9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://message-broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@message-broker:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092",
        ]
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 20s
    deploy:
      replicas: ${GREENWAVE_LISTENERS:-1}

  jaeger:
    image: quay.io/jaegertracing/all-in-one:latest@sha256:ab6f1a1f0fb49ea08bcd19f6b84f6081d0d44b364b6de148e1798eb5816bacac
    ports:
      - 127.0.0.1:6831:6831/udp
      - 127.0.0.1:6832:6832/udp
      - 127.0.0.1:5778:5778
      - 127.0.0.1:16686:16686
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318
      - 127.0.0.1:14250:14250
      - 127.0.0.1:14268:14268
      - 127.0.0.1:14269:14269
      - 127.0.0.1:9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

networks:
  default:
    driver: bridge
